services:
  - type: web
    name: cliente-backend
    runtime: java
    buildCommand: bash ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 10000
